services:
  db:
    image: mariadb:10.5.8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: ramada
      MYSQL_USER: ramada
      MYSQL_PASSWORD: ramada
    networks:
      - default
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: toor
      UPLOAD_LIMIT: 300M
    networks:
      - default
  back:
    depends_on:
      - db
    build: ./back
    image: ramada_back
    container_name: ramada_back
    ports:
      - '3001:3001'
    restart: always
    environment:
      API_PORT: 3001
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ramada
      DB_USER: ramada
      DB_PASSWORD: ramada

    networks:
      - default
  front:
    depends_on:
      - back
    build: ./front
    image: ramada_front
    container_name: ramada_front
    ports:
      - '8000:8000'
    restart: always
    environment:
      API_URL: http://back:3001
      DB_CONNECTION: sqlite
    networks:
      - default
networks:
  default:
volumes:
  db_data:
